language: node_js
node_js:
- 8
script:
- npm run build
branches:
  only:
  - gh-pages
  - "/.*/"
deploy:
  provider: heroku
  api_key:
    secure: R90E9lhKPaOm7gpv1pq5x2SkNme+9NQByzlpoO1eRp/qY5H9Qdb3HStGPn+FG9mqq3FX5+X/CxUVyNNpZ1n1a5BLP7O5Y+tmXxbxg5XK53n28U+p4T/76SdESuyireM5AhEPRhimnyTfQI1GMsLbVCFrPicntNhV4g9CpzziOQ87ayhIkVOm8S/pig319xfZ+IIcxTbiIxXju5B/Ie8vFH/uv8iAGlqXiM/C69Is7hQB68/ArzaZwPDflO1ph8L1T2MrOhbm8/2uWi8fZLu5FeTCr3po7ZoapYsXAiqLaIcu5hIZ11xANw4QSz6dGo6McOW1sVof8HF0v3uBGG6W6pCUjC6ZQReZXRIUEBxMSk7WiHPIppFgSlAwD5NHoba26Cznd0AfPFGDT3XVcpm0NO2i3m6U1dJd97r0KQnvx0+/owBemw22169Z5Ol8qsNAK2CkngPiXAjq5/FZf4C6sC6fEAYzBdJYvBVeINWTz8NnZ/ykp1OVqhnR8x2bQRjS8ctdF8BQ4fhAxVS9lCutHkV5emGXemINioQhvV+owJ3hftuznihcDwKQFI2hM4VYW0484hE87PvQ5WLrAIooy/mk7XFcAaerPn61FyeTCwn3yDZS5+jWz4IeedUF02BlaBXq3eGVXrARC1SqMhYs8PE66aAV+aHjNiPP72a7ggc=
