language: node_js
node_js:
- 8
script:
- npm run build
branches:
  only:
  - gh-pages
  - "/.*/"
deploy:
  provider: heroku
  api_key:
    secure: oenHSGu7zRNji3R7t+mbweTcgxv5cG8QFfxAHU3/trZafitLyIqcXJ8KJJdW57j6QSOTu01XxgOuw0PH/YxoyR8CCAvM2VZwXKtsuE17AgLT6PvTImASYCp4IFjk885Zb/nh66ySOsaB7fKTNUHAfleU6Wxdw4vQ+45++B0T3pr5aYu8tHxAifdx8mhqAIxOBvZP2oSzY3UM0t08YMViF2YMC1EQJphMBrGf4B1neWQYx66VGwQZXZMkAZal+J5AK1HSqwTIOCgmAfhMJUOq/bDJhvCgyTGFK0J1b7hc0vJPCvwwLqQQZzbPlNCDN+v9100s7wkEZn0vpA6UAcy1lYPMi2A2eK437k4QDEeL8On7GiwETO3rtPFhj6rNnR88f1mpz/V4yofGA2/l9aF+E7sjRa+IPQ4I59193NZrSpX1TcXZAB8TSFgZ5aSwJdR05i7DfiUkmvncjgxo4S7xdSglVHB+CX96URVqePkaqZsnvrTbRFUY0IwjpTXWeivCNsJgoHM4K/T1sA48uPwKitpDDK9glBeHkFEIdPxrhDN1gFDtSY6jS/HSkk3SUIbmSAyU333WXF6fSUduaLgzQpBfhdj1vJL2r+WKeGi5UxNWjn9YIdVckh3L7AW80FdBjN6ZDUykTM4biNhzRSw2K9iTKpPa0XYLx1oWc/+afIg=
