version: '3.1'

services:
  outpost:
    build: .
    ports:
      - 8081:8081
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: my_pass